#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
fabric-ca-server:
   image: tjfoc/gmca
   container_name: fabric-ca-server
   ports:
     - "7054:7054"
   environment:
     - FABRIC_CA_HOME=/etc/tjfoc/gmca-server
   volumes:
     - "./fabric-ca-server:/etc/tjfoc/gmca-server"
   command: sh -c 'fabric-ca-server start -b admin:adminpw'
